remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Hello and Welcome to The Crochet Snake, all thibgs fabric!
description: The Crochet Snake, all things crochet, knitting, and weaving!

show_downloads: false
